**Tensor Basics, initialization, and indexing**

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)  
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3, 8 , 90.])
print(tensor_one_d)  

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [4]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([
    [[1,2,0],[3,5,-1]],

     [[10,2,0],[1,0,2]],

      [[5,8,0],[2,7,0]],

       [[2,1,9],[4,-3,32]]

       ])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [6]:
print(tensor_three_d.shape)

(4, 2, 3)


In [7]:
print(tensor_three_d.ndim)

3


In [8]:
# build a 4D tensor using 3D ones?

In [9]:
# randomize a fixed shaped tensor
#tf.random.set_seed(1234)
#print(tf.random.uniform([1]))
tf.random.uniform(shape=[3,4,2,3], dtype=tf.float32, seed=1234)

<tf.Tensor: shape=(3, 4, 2, 3), dtype=float32, numpy=
array([[[[0.848307  , 0.32357132, 0.3067001 ],
         [0.06969976, 0.9138565 , 0.17047906]],

        [[0.2833712 , 0.35627055, 0.54155624],
         [0.07525682, 0.07449007, 0.86595404]],

        [[0.5590595 , 0.00934196, 0.06701303],
         [0.49774456, 0.2989055 , 0.8094423 ]],

        [[0.6584983 , 0.48154235, 0.15170729],
         [0.5910175 , 0.33441043, 0.15515935]]],


       [[[0.24549198, 0.13945496, 0.98694456],
         [0.90309167, 0.15221   , 0.02298522]],

        [[0.7943164 , 0.66823316, 0.76234066],
         [0.9573715 , 0.81357455, 0.20782101]],

        [[0.8659394 , 0.10141969, 0.22649705],
         [0.03172696, 0.18611705, 0.43014538]],

        [[0.12050104, 0.24348867, 0.35743213],
         [0.19433928, 0.1919595 , 0.29035628]]],


       [[[0.83578694, 0.92807364, 0.8308325 ],
         [0.05831671, 0.30794823, 0.9126067 ]],

        [[0.39535117, 0.78672135, 0.38925326],
         [0.09642875, 0.6395473

In [10]:
# convert the dtype of a tensor using cast

tensor_one_d = tf.constant([2,0,-3, 8 , 90.])
int_cast = tf.cast(tensor_one_d,dtype=tf.int16)
print(int_cast)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [11]:
# string tensor
string_tensor = tf.constant(["hello","hey","hi world"])
print(string_tensor)

tf.Tensor([b'hello' b'hey' b'hi world'], shape=(3,), dtype=string)


In [12]:
# convert a np array into a tensor
import numpy as np

np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [13]:
tensor_from_np = tf.convert_to_tensor(np_array)
print(tensor_from_np)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [14]:
# eye function: make an identity matrix
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=None, #if 5, the 5x5 is cut off
    batch_shape=[2,], #the extrtnal variable of the matrix; can be [2,4] 
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [15]:
# filling values: fill()

fill_tensor = tf.fill(
    [1,3,4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [16]:
# ones method: a tensor with values 1

ones_tensor = tf.ones(
    [3,14],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(3, 14), dtype=float32)


In [17]:
# one_like: change a tensor into 1s while keeping the same shape

one_like_tensor = tf.ones_like(fill_tensor)
print(one_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [18]:
# zeroes: all into 0s

zeros_tensor = tf.zeros(
    [3,12],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(3, 12), dtype=float32)


In [21]:
# shape

print(fill_tensor.shape)
print(zeros_tensor.shape)

(1, 3, 4)
(3, 12)


In [23]:
print(tf.shape(zeros_tensor))

tf.Tensor([ 3 12], shape=(2,), dtype=int32)


In [24]:
# rank: return the rank/degree of a tensor
# The total number of indices required to identify each component uniquely

t = tf.constant([[1,1,1],[2,2,2],[3,3,3]])
print(tf.rank(t))

tf.Tensor(2, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [42]:
# random tensor
# https://www.tensorflow.org/api_docs/python/tf/random#functions

random_tensor = tf.random.normal(
    [3,3],
    mean=3.5, 
    stddev=0.05, 
    dtype = tf.dtypes.float32,
    seed=10,
    name=None
)
print(random_tensor)

tf.Tensor(
[[3.581843  3.5500941 3.562877 ]
 [3.522506  3.555683  3.4404898]
 [3.4812856 3.4558072 3.4982846]], shape=(3, 3), dtype=float32)


In [41]:
# uniform: each value has equal chance of being picked (a rectangle area); while normal distribution means
# gravity surroudning the mean.
random_tensor2 = tf.random.uniform(
    [3,3],
    minval=0,
    maxval=8000,
    dtype=tf.dtypes.int32,
    seed=10,
    name=None
)
print(random_tensor2)

tf.Tensor(
[[4840 5452 2915]
 [7717  362 7862]
 [5973 4435 7969]], shape=(3, 3), dtype=int32)


In [44]:
print(tf.random.uniform([2]))


tf.Tensor([0.17574668 0.8374188 ], shape=(2,), dtype=float32)


In [52]:
# Indices for tensors

tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)

print(tensor_indexed[0:4]) #slicing
print(tensor_indexed[4:])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6 66  7], shape=(3,), dtype=int32)


In [62]:
# index for 2d tensors
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d[0:3, :]) # first ROWS then COLUMNS

print(tensor_two_d[2, :]) #colon: pick up all indices

print(tensor_two_d[2, 1:]) 

print(tensor_two_d[... , 1]) # first print ROWS then COLUMNS

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
tf.Tensor([1 5 6], shape=(3,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [63]:
# 3d example
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [65]:
print(tensor_three_d[0,:,:]) # the first ELEMENT

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [67]:
print(tensor_three_d[:,0,:]) #the 0th element of the 2 groups

tf.Tensor(
[[ 1  2  0]
 [10  2  0]
 [ 5  8  0]
 [ 2  1  9]], shape=(4, 3), dtype=int32)


In [70]:
print(tensor_three_d[:,:,0]) #column values for the first elements

tf.Tensor(
[[ 1  3]
 [10  1]
 [ 5  2]
 [ 2  4]], shape=(4, 2), dtype=int32)


In [71]:
print(tensor_three_d[0,:,2])

tf.Tensor([ 0 -1], shape=(2,), dtype=int32)


In [72]:
print(tensor_three_d[0:2,:,2])

tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)
