tensorflow: math operations and linear algebra 

In [ ]:
import tensorflow as tf

math lib https://www.tensorflow.org/api_docs/python/tf/math

In [ ]:
# absolute values
x = tf.constant([-2.25, 3.25])
tf.abs(x)

# if the numbers are like a + bj , the abs would be sqrt(a^2 + b^2)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
# addition

x1 = [1, 2, 3, 4, 5]
x2 = [3, 4, 5, 6, 7]

print(tf.add(x1, x2)) #substract, multiply, divide
# tensors can be divided by nan or 0 using: https://www.tensorflow.org/api_docs/python/tf/math/divide_no_nan


tf.Tensor([ 4  6  8 10 12], shape=(5,), dtype=int32)


In [ ]:
# elementwise multiplications

x2_single = [9]
print(tf.add(x1, x2_single))

tf.Tensor([10 11 12 13 14], shape=(5,), dtype=int32)


In [ ]:
# multiplication between different sizes of tensors

x1 = tf.constant([[1, 2, 3, 4, 5, 6]], dtype = tf.float32)
x2 = tf.constant([[1],[2],[3]], dtype = tf.float32)

print(x1.shape)
print(x2.shape)

print(tf.math.multiply(x1, x2))

(1, 6)
(3, 1)
tf.Tensor(
[[ 1.  2.  3.  4.  5.  6.]
 [ 2.  4.  6.  8. 10. 12.]
 [ 3.  6.  9. 12. 15. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
# element wise maximum: Returns the index with the largest value across axes of a tensor.

B = tf.constant([[2, 20, 30, 3, 6], 
                  [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(B.shape)
print(tf.math.argmax(B,axis=0)) #0: compare column elements (controlling rows)
print(tf.math.argmax(B,axis=1)) #1: compare column elements (controlling columns)

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [ ]:
# compare tensors to see whether they are equal

x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
# pow: power of one value to another
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
# reduce_sum: Computes the sum of elements across dimensions of a tensor.

x = tf.constant([[1, 1, 1], [1, 1, 1]]) #shape: 2,3
print(tf.reduce_sum(x).numpy()) # reduce across all dimensions
print(tf.reduce_sum(x, 0).numpy()) # reduce across the first dimension 
# [1, 1, 1] + [1, 1, 1] = [2, 2, 2]
print(tf.reduce_sum(x, 1).numpy()) # reduce across the second dimension -  
# [1, 1] + [1, 1] + [1, 1] = [3, 3]

# also reduce_max, reduce_min, reduce_std, reduce_mean, ...

6
[2 2 2]
[3 3]


In [ ]:
# sigmoid
x = tf.constant([0.0, 1.0, 50.0, 100.0])
print(tf.math.sigmoid(x))

tf.Tensor([0.5       0.7310586 1.        1.       ], shape=(4,), dtype=float32)


In [ ]:
# top-k: top k values of an array

result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=3)
print(result.values.numpy())

[99 98 96]


linear algebra
https://www.tensorflow.org/api_docs/python/tf/linalg

In [ ]:
# linalg.matmal : matrix multiplication

x1 = tf.constant([[1,2,0],
                 [3,5,-1]])
x2 = tf.constant([[1,2,0],
                 [3,5,-1],
                  [4,5,6]])
print(tf.matmul(x1, x2)) 
print(x1@x2) #reduce way
# notice: (2,3) and (3,2) MUST share the same columns for the first vector ("3"); output size: (2,2)

tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)


In [ ]:
# transpose
tf.transpose(x1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [28]:
x1_3d = tf.constant([
    [[1,2],[3,5]],

     [[10,2],[1,0]],

      [[5,8],[2,7]]

       ])

x2_3d = tf.constant([
    [[5,1,4],[34,15,1]],

     [[1,2,2],[5,3,2]],

      [[2,2,3],[1,1,1]]

       ])



# how to make batch multiplication, 
# revise the batch of x1_3d to 2,3 ([[1,2],[3,5]]) is called a batch
x1_3d@x2_3d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 73,  31,   6],
        [185,  78,  17]],

       [[ 20,  26,  24],
        [  1,   2,   2]],

       [[ 18,  18,  23],
        [ 11,  11,  13]]], dtype=int32)>

In [31]:
# band_part: Copy a tensor setting everything outside a central band in each innermost matrix to zero.
# cut off the matrix to form different triangles

tensor_two_d = tf.constant([[1,2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]
                            ], dtype = tf.float16)

#### condition: (lower<0 or m-n <= lower) and (upper>0 or n-m >= upper); 
#### if True, keep value; if False, return 0
# m -- rows, n -- columns

# tf.linalg.band_part(input, 0, -1) ==> Upper triangular part.
# tf.linalg.band_part(input, -1, 0) ==> Lower triangular part.
# tf.linalg.band_part(input, 0, 0) ==> Diagonal.

print(tf.linalg.band_part(tensor_two_d,0,0))

# intermediate computation includes matrices of n-m and m-n
tensor_m_n = tf.constant([
    [0,-1,-2],
    [1,0,-1],
    [2,1,0],
    [3,2,1]
])
tensor_n_m = tf.constant([
    [0,1,2],
    [-1,0,1],
    [-2,-1,0],
    [-3,-2,-1]
])

tf.Tensor(
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 6.]
 [0. 0. 0.]], shape=(4, 3), dtype=float16)


In [38]:
# other topics: cholesky, determinant, cross product, inverse, trace, svd

# inverse: shape must be (n,n)
inv1 = tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6]
], dtype = tf.float16)
tf.linalg.inv(inv1)


<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 0.741  , -0.01892,  0.3154 ],
       [-0.1294 , -0.00946,  0.1577 ],
       [-0.01578,  0.01104, -0.01735]], dtype=float16)>

In [44]:
# svd: a decomposition method to get rid of non-important values
svd_matrix_A = tf.constant([[2, 3], [4, 5], [6, 7]], dtype=tf.float32)
s,u,v = tf.linalg.svd(svd_matrix_A)
print(s)
print(u)
print(v)

tf.Tensor([11.782492    0.41578525], shape=(2,), dtype=float32)
tf.Tensor(
[[ 0.30449855 -0.86058956]
 [ 0.54340035 -0.19506174]
 [ 0.78230214  0.47046405]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 0.63453555  0.7728936 ]
 [ 0.7728936  -0.63453555]], shape=(2, 2), dtype=float32)


In [3]:
# einsum operator: Tensor contraction over specified indices and outer product.
# note: always remember the shapes of vectors

import numpy as np

A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

B = np.array([[2,9,0,3,0],
              [3,6,8,-2,2],
              [1,3,5,0,1],
              [3,0,2,0,5]])

print(A.shape)
print(B.shape)

# compare normal multiplication with eisum
print("matmul C = : \n")
print(A@B)

print("Einsum C = : \n")
print(np.einsum('ij,jk -> ik',A,B))

(3, 4)
(4, 5)
matmul C = : 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]
Einsum C = : 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [6]:
# use eisum to do element wise multiplication

A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

B = np.array([[2,9,0,3],
              [3,6,8,-2],
              [1,3,5,0]])

print(A*B)
print('\n')

print(np.einsum('ij,ij -> ij',A,B))

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [9]:
# use eisum to do transpose

A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

print(A.T)
print('\n')

print(np.einsum('ij -> ji',A))

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [13]:
# einsum: 3d batch size multiplication
# 2,3,4 * 2,4,5 > 2,3,5, b=2

A = np.array([
    [[2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]],

    [[1,3,1,12],
     [0,2,2,0],
     [1,5,4,1]]
])

B = np.array([[[2,9,0,3,0],
              [3,6,8,-2,2],
              [1,3,5,0,1],
              [3,0,2,0,5]],

              [[1,0,0,3,0],
               [3,0,4,-2,2],
               [1,0,2,0,0],
               [3,0,1,1,0]]
              ])


print(np.matmul(A,B))
print('\n')

print(np.einsum('bij, bjk -> bik',A,B))

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[47  0 26  9  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[47  0 26  9  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [18]:
# einsum: sum all values in a matrix

A = np.array([
    [[2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]],

    [[1,3,1,12],
     [0,2,2,0],
     [1,5,4,1]]
])

print(np.sum(A))

print(np.einsum('bij ->',A)) # no output in the expression
print(np.einsum('bij -> i',A)) #sum based on row/column

62
62
[32  9 21]


In [20]:
# use einsum in tranformer "attention is all you need"
# Q = batchsize, s_q, modelsize
# K = batchsize, s_k, modelsize
Q = np.random.randn(32,64,512)
K = np.random.randn(32,128,512)
np.einsum('bqm,bkm -> bqk',Q,K)

array([[[-20.05480624, -15.70538446,   0.73358182, ...,  23.98429253,
         -22.63725417, -30.51670629],
        [ -6.00787556, -34.19752824,  17.68195354, ...,  14.2491985 ,
          68.29136109,  48.62513724],
        [ 14.72195587,  20.37025903, -39.69948707, ...,  36.08727589,
          28.44312801, -50.12192838],
        ...,
        [  2.94206806,   5.68038905, -31.91790005, ...,  17.9867567 ,
          -0.12667798,  15.51827343],
        [ -2.18742835, -19.67843661, -29.56721858, ...,  39.91968505,
         -21.98588681,  28.66207116],
        [ 18.30796718, -36.64981376,  40.22731102, ...,  27.6994861 ,
          14.20156659, -17.04945364]],

       [[-40.72655756,  20.40109326,   0.49974743, ...,   4.32443312,
          -8.56306289,  -1.09277158],
        [  5.52409877, -28.36591621,  -8.19468957, ..., -35.8277312 ,
           7.5466967 ,  25.8848114 ],
        [ -7.85355887,  24.87401834, -36.46368493, ...,   1.57212071,
           5.82642421, -25.74202898],
        ...,


In [24]:
# einsum in "reformer: the efficient transformer"
A = np.random.randn(2,4,4,2) #bcij
B = np.random.randn(2,4,4,1) #bcik
print(np.einsum('bcik,bcij -> bckj',B,A).shape) #ik to kj is a transpose

(2, 4, 1, 2)
