Ragged tensors, sparse tensors, string tensors, and variables

ragged tensors

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# ragged tensors

tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

print(tensor_two_d.shape)

#ragged: if this tensor is not rectangular, you cannot print out the shape in the normal way

(4, 3)


In [3]:
tensor_ragged = tf.ragged.constant([
    [1,2,0],
    [3,],
    [1,5,6,5,6],
    [2,3]
])
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [4]:
# boolean mask a (ragged) tensor
# 2-D example
tensor = [[1, 2], [3, 4], [5, 6]]
mask1 = np.array([True, False, True])
mask2 = np.array([[True, False],[True,True],[False, False]])
print(tf.boolean_mask(tensor, mask1))  # [[1, 2], [5, 6]]

print(tf.boolean_mask(tensor, mask2)) #[1 3 4]

tf.Tensor(
[[1 2]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([1 3 4], shape=(3,), dtype=int32)


In [5]:
# use values and row length to create ragged tensors

print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [6]:
# create a ragged tensor with row limits

print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [7]:
# create a ragged tensor with row splitting indices

print(tf.RaggedTensor.from_row_splits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_splits=[0, 4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [8]:
# convert a regular tensor to a ragged one

dt = tf.constant([[5, 7, 0], [0, 3, 0], [6, 0, 0]])
tf.RaggedTensor.from_tensor(dt)

tf.RaggedTensor.from_tensor(dt, lengths=[1, 0, 3]) #use length to limit the output elements


<tf.RaggedTensor [[5], [], [6, 0, 0]]>

sparse tensors

In [9]:
# create a sparse tensor

tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values = [11,56], dense_shape=[5,7]
)
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 7], shape=(2,), dtype=int64))


In [10]:
# convert it to a full view

tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 7), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int32)>

string tensors

In [11]:
tensor_string = tf.constant(["hello","I am","a string"])
print(tensor_string)

tf.Tensor([b'hello' b'I am' b'a string'], shape=(3,), dtype=string)


In [12]:
# join together
tf.strings.join(['abc','def'],separator="  ").numpy()

b'abc  def'

In [13]:
# length, lower, upper, ngrams

*variables*
https://www.tensorflow.org/api_docs/python/tf/Variable

In [14]:
x = tf.constant([1,2])
x_var = tf.Variable(x,name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [15]:
# assigning after substracting some values
x_var.assign_sub([3,8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -6], dtype=int32)>

In [16]:
# you can use gpu or tpu to assign variables (e.g. define on cpu and compute on gpu)
with tf.device('GPU:0'): # CPU:0
  x_var = tf.Variable(0.2)
print(x_var.device)

/job:localhost/replica:0/task:0/device:GPU:0
